name: "Newman Tests"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: postman/newman:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: List files (debugging)
        run: ls -la  # Helps verify files exist

      - name: Run API Tests
        run: newman run ai-assisted-postman-collection.json -e new-env-postman_environment.json

      - name: Output the run Details
        uses: actions/upload-artifact@v6
        with: 
          name: RunReports
          path: testResults